### ISSUE TITLE
"msg is not defined" when includeActions: true

### ISSUE THREAD

**Issue by flic** [webdeck/homebridge-indigo#1]
I'm getting the following error message when includeActions is true:

```
    "name": "Utebelysning [Tänd]",
    "nameURLEncoded": "Utebelysning%20%5BT%C3%A4nd%5D",
    "restParent": "actions",
    "restURL": "/actions/Utebelysning%20%5BT%C3%A4nd%5D.json"
}
```

]

/usr/local/lib/node_modules/homebridge-indigo/index.js:157
                callback(msg);
                         ^

ReferenceError: msg is not defined
    at IndigoPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-indigo/index.js:157:26)
    at IndigoPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-indigo/index.js:266:21)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-indigo/node_modules/request/request.js:373:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-indigo/node_modules/request/request.js:1318:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-indigo/node_modules/request/request.js:1266:12)
    at emitNone (events.js:72:20)

**Comment by webdeck** [comment]
Note that the bug was obscuring the real error message.  I pushed the fix to npm as well.  If you re-install and re-run, you will see a different error for this device, which is the real error.  Please submit another issue ticket with that error message.  Thanks.
