### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by livefeed** [webdeck/homebridge-indigo#26]
Everything is up to date as of now but getting this error;

[9/17/2017, 8:11:46 PM] [My Indigo Server] Indigo base URL is http://127.0.0.1:8176
/Users/martinc/.nvm/versions/node/v4.2.4/lib/node_modules/homebridge/lib/api.js:108
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/Users/martinc/.nvm/versions/node/v4.2.4/lib/node_modules/homebridge/lib/api.js:108:11)
    at Server._loadPlatforms (/Users/martinc/.nvm/versions/node/v4.2.4/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/Users/martinc/.nvm/versions/node/v4.2.4/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/Users/martinc/.nvm/versions/node/v4.2.4/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/Users/martinc/.nvm/versions/node/v4.2.4/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

**Comment by webdeck** [comment]
What's in your config.json file?
